name: Deploy Emerge LMS to Server

on:
  push:
    branches:
      - master  # Deploy on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3  # Updated to latest version
      with:
        node-version: '18'

    - name: Cache Node Modules
      uses: actions/cache@v3  # Optional step
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Upload Files to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        SOURCE: "build/" # React build folder
        TARGET: "/var/www/emergekenya.org" # Destination path on server

    - name: Restart Nginx (Optional, requires sudo access)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          sudo systemctl restart nginx
