name: Deploy Emerge LMS to Server

on:
  push:
    branches:
      - master  # Deploy on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: '18'

    - name: Cache Node Modules
      uses: actions/cache@v3 
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Upload Files to Server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "build/" # React build folder
        target: '/home/aaaplatforms/daruur-lms/daruur-lms-frontend'

    # - name: Restart Nginx in Docker
    #   uses: appleboy/ssh-action@v0.1.5
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     script: |
    #     docker exec nginx-server nginx -s reload
    #     script: |
    #     sh
    #     pm2 ls
