name: Deploy Emerge LMS to Server

on:
  push:
    branches:
      - master  # Deploy on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 22
          source: 'build/*'
          target: '/home/aaaplatforms/daruur-lms/daruur-lms-frontend'
          debug: true

    # - name: Restart Nginx in Docker
    #   uses: appleboy/ssh-action@v0.1.5
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #     docker exec nginx-server nginx -s reload
    #     script: |
    #     sh
    #     pm2 ls
